fwitter/urls.py
from django.urls import path

from . import views

app_name='fwitter'
urlpatterns = [
    path('', views.index, name='index'),#goes to the basic index page if no specifiers are made
    path('<int:user_id>/userposts', views.user, name='user'),#goes to the page with the tweets of a specific user
    path('<int:tweet_id>/tweet', views.tweet, name='tweet'),#goes to the page of a specific tweet
    path('<int:user_id>/details', views.detail, name='detail'),#goes to a users page
    path('topics/<int:topic_id>', views.topic, name='topic')#goes to page with topics 
]

myapp/urls.py
#python 3.7.4
#django 3.0.3
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('fwitter/', include('fwitter.urls')),#goes to the actual website stuff
    path('admin/', admin.site.urls),#goes to the admin page
]

fwitter/models.py
import datetime
from django.db import models
from django.utils import timezone

class User(models.Model):
    username = models.CharField(max_length=200)#data field for user's username
    first_name = models.CharField(max_length=200)#data field for users first name
    last_name = models.CharField(max_length=200)#data field for user's last name
    password = models.CharField(max_length=200)#data field for user's last name
    def __str__(self):
        return self.username#displays username if asked for

class Topic(models.Model):
    topic_text = models.CharField(max_length=200)#data field for a topic
    def __str__(self):
        return self.topic_text#displays topic if asked for

class Tweet(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)#connects user with a tweet
    tweet_text = models.CharField(max_length=200)#data field for a tweet
    pub_date = models.DateTimeField('date published')#gets the time of when the tweet was made
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)#connects topics with a tweet
    def __str__(self):
        return self.tweet_text#displays tweet if asked for
    def was_published_recently(self):
        return timezone.now() - datetime.timedelta(days=1) <= self.pub_date <= timezone.now()#displays if tweet was posted recently if asked for
        

fwitter/views.py
#python 3.7
#django 3.0.3
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from .models import Tweet, User, Topic
from django.contrib.auth import authenticate, login, logout




def index(request):#function for if someone goes to the index page
    if request.POST:#if something in the page was updated...
        if "inputUsername" in request.POST.keys():#if someone submitted a username...
            user = authenticate(username=request.POST['inputUsername'],password=request.POST['inputPassword'])#how does the authenticate function get user information? do i have to use the django user object?
            if user is not None:#if the information is correct...
                login(request, user)#login the user
        elif 'logout' in request.POST.keys():#if someone pressed the button to log out...
            logout(request)#logout the user

    if request.user.is_authenticated:#if the users information has been authenticated...(something went wrong here)
        loggedIn = True#Boolean value that will determine what message/abilities appear at the top of the screen
    else:
        loggedIn = False

        
    latest_tweet_list = Tweet.objects.order_by('-pub_date')[:10]#Data value that contains the 10 most recent tweets
    context = {'latest_tweet_list': latest_tweet_list, 'loggedIn':loggedIn, 'user':request.user,}#arraylist of objects necessary in the template
    return render(request, 'fwitter/index.html', context)#sends objects to the template

def user(request, user_id):
    user = User.objects.get(pk=user_id)#picks out the user from the given user id
    return render(request, 'fwitter/user.html', {'user':user})#send the users information to te template

def tweet(request, tweet_id):
    tweet = Tweet.objects.get(pk=tweet_id)#picks out a tweet from the given tweet id
    return render(request, 'fwitter/tweet.html', {'tweet':tweet})#send the tweet information to the template

def detail(request, user_id):
    user = get_object_or_404(User, pk=user_id)#retrieves user information if valid
    return render(request, 'fwitter/detail.html', {'user': user})#sends the user information to the template

def topic(request, topic_id):
    topic = Topic.objects.get(pk=topic_id)
    return render(request, 'fwitter/topic.html', {'topic':topic})
    

fwitter/templates/fwitter/detail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>detail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </head>
  <body>

    <div class="row">
      <div class="col-xl-6">
        <img width="50%" class="" src="https://upload.wikimedia.org/wikipedia/commons/f/f0/Error.svg"/>
        <p class="p1">{{user.first_name}} {{user.last_name}}</p>
        <p class="p1">{{user.username}}</p>
      </div>
      <div class="col-xl-6">
        {% for tweet in user.tweet_set.all %}
        <div class="media border p-3">
          <img src="https://upload.wikimedia.org/wikipedia/commons/f/f0/Error.svg" alt="Photo error!" class="mr-3 mt-3 rounded-circle" style="width:60px;">
          <div class="media-body">
            <h4><a href="/fwitter/{{ user.id }}/details">{{user.first_name}} {{user.last_name}}</a><small><i> {{tweet.pub_date}}</i></small></h4>
            <p>{{ tweet.tweet_text }}</p>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>

  </body>
</html>

fwitter/templates/fwitter/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Homepage</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </head>
  <body>
    <h1>Fwitter</h1>
    {% if loggedIn %}

    <h3>Logged in as <i>{{user.username}}</i> ({{user.first_name}} {{user.last_name}})</h3>

    <form style="padding-bottom:len;" method="post">
      {% csrf_token %}
      <input type="hidden" name="logout" value="logout"></input>
      <button type="submit" class="btn btn-danger">Logout</button>
    </form>

    {% else %}

    <form style="padding-bottom:len;" method="post">
        {% csrf_token %}

        <div class="form-group">
          <label for="inputUsername">Username</label>
          <input type="text" class="form-control" name="inputUsername" id="inputUsername" />
        </div>

        <div class="form-group">
          <label for="inputPassword">Password</label>
          <input type="password" class="form-control" name="inputPassword" id="inputPassword" />
        </div>

        <button type="submit" class="btn btn-danger">Login</button>

    {% endif %}

    {% if latest_tweet_list %}
      {% for tweet in latest_tweet_list %}
      <div class="media border p-3">
        <img src="https://upload.wikimedia.org/wikipedia/commons/f/f0/Error.svg" alt="Photo error!" class="mr-3 mt-3 rounded-circle" style="width:60px;">
        <div class="media-body">
          <h4><a href="/fwitter/{{ tweet.user.id }}/details">{{tweet.user.first_name}} {{tweet.user.last_name}}</a><small><i> {{tweet.pub_date}}</i></small></h4>
          <p>{{ tweet.tweet_text }}</p>
        </div>
      </div>
        {% endfor %}
    {% else %}
      <p>No tweets are available.</p>
    {% endif %}
  </body>
</html>

fwitter/templates/fwitter/topic.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Topic page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </head>
  <body>
    <h1>{{ topic.topic_text }}</h1>
      {% for tweet in topic.tweet_set.all %}
      <div class="media border p-3">
        <img src="https://upload.wikimedia.org/wikipedia/commons/f/f0/Error.svg" alt="Photo error!" class="mr-3 mt-3 rounded-circle" style="width:60px;">
        <div class="media-body">
          <h4><a href="/fwitter/{{ tweet.user.id }}/userposts">{{tweet.user.first_name}} {{tweet.user.last_name}}</a><small><i> {{tweet.pub_date}}</i></small></h4>
          <p>{{ tweet.tweet_text }}</p>
        </div>
      </div>
      {% endfor %}
  </body>
</html>

fwitter/templates/fwitter/tweet.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Tweetpage</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </head>
  <body>
    {% for user in tweet %}
    <h1>{{user.username }}</h1>
      <div class="media border p-3">
        <img src="https://upload.wikimedia.org/wikipedia/commons/f/f0/Error.svg" alt="Photo error!" class="mr-3 mt-3 rounded-circle" style="width:60px;">
        <div class="media-body">
          <h4>{{user.first_name}} {{user.last_name}}<small><i>{{tweet.pub_date}}</i></small></h4>
          <p>{{ tweet.tweet_text }}</p>
        </div>
      </div>
      {{% endfor %}}
  </body>
</html>

fwitter/templates/fwitter/user.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Userpage</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </head>
  <body>
    <h1>{{ user.username }}</h1>
      {% for tweet in user.tweet_set.all %}
      <div class="media border p-3">
        <img src="https://upload.wikimedia.org/wikipedia/commons/f/f0/Error.svg" alt="Photo error!" class="mr-3 mt-3 rounded-circle" style="width:60px;">
        <div class="media-body">
          <h4><a href="/fwitter/{{ tweet.user.id }}/userposts">{{user.first_name}} {{user.last_name}}</a><small><i> {{tweet.pub_date}}</i></small></h4>
          <p>{{ tweet.tweet_text }}</p>
        </div>
      </div>
      {% endfor %}
  </body>
</html>